# GitHub Dependabot configuration file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "biz.aQute.bnd:biz.aQute.bndlib"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "biz.aQute.bnd:bnd-maven-plugin"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "org.apache.derby:derby"
        versions:
          - ">=10.15.0" # does not support java 8
      - dependency-name: "org.springframework:spring-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.apache.openjpa:openjpa"
        versions:
          - ">=4.0.0" # does not support java 8
      - dependency-name: "org.mockito:mockito*"
        versions:
          - ">=5.0.0" # does not support java 8

  - package-ecosystem: "maven"
    directory: "/application"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/sandbox"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/subsystem/subsystem-scope-api"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/subsystem/subsystem-scope-impl"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/subsystem/subsystem-scope-itests"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/tutorials"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"

