# GitHub Dependabot configuration file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/spi-fly"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        versions:
          - ">=6.0.0"
      - dependency-name: "biz.aQute.bnd:biz.aQute.bndlib"
        versions:
          - ">=7.0.0"
